# Generated by Django 5.2.13 on 2026-04-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('cpu', models.CharField(blank=True, default='', max_length=100)),
                ('ram', models.IntegerField(default=0)),
                ('rom', models.IntegerField(default=0)),
                ('charging', models.IntegerField(default=0)),
                ('battery', models.IntegerField(default=0)),
                ('screen_refresh_rate', models.IntegerField(default=60)),
                ('screen_resolution', models.CharField(blank=True, default='', max_length=20)),
                ('weight', models.IntegerField(default=0)),
                ('front_camera', models.IntegerField(default=0)),
                ('rear_camera', models.IntegerField(default=0)),
                ('screen_size', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
    ]
